### ISSUE TITLE
Gebruik geen onnodige px units

### ISSUE THREAD

**Issue by joostf** [fatimahilali/fix-the-flow-interactive-website#10]
https://github.com/fatimahilali/fix-the-flow-interactive-website/blob/97f2f3a4a67814e3f4c7c2679e00b9d18a496a55/styles/style.css#L79

Voor CSS properties die context afhankelijk kunnen zijn altijd dynamische units gebruiken

https://medium.com/@shakirulhkhan/why-should-you-not-use-px-3021aa0b5958

**Comment by fatimahilali** [comment]
Ik gebruikte voorheen altijd px, maar probeer dit nu te vermijden door dynamische units te gebruiken. Soms vergeet ik het nog, maar ik blijf eraan werken om mijn CSS flexibeler en responsiever te maken.
