### ISSUE TITLE
Gebruik animatable properties om elementen te verbergen

### ISSUE THREAD

**Issue by joostf** [fatimahilali/fix-the-flow-interactive-website#11]
https://github.com/fatimahilali/fix-the-flow-interactive-website/blob/97f2f3a4a67814e3f4c7c2679e00b9d18a496a55/styles/style.css#L156

De `diplay` property is niet animatable. Als je bijvoorbeeld `opacity` gebruikt kan je de zichtbaarheid van het element animeren. Dat kan helpen om een fijnere gebruikerservaring te bieden.

**Comment by fatimahilali** [comment]
Dit wist ik niet. Ik neem dit mee en zal het in de toekomst toepassen om interacties gebruiksvriendelijker te maken.
