### ISSUE TITLE
Voorkom het gebruiken van een id selector (#)

### ISSUE THREAD

**Issue by joostf** [fatimahilali/fix-the-flow-interactive-website#12]
https://github.com/fatimahilali/fix-the-flow-interactive-website/blob/97f2f3a4a67814e3f4c7c2679e00b9d18a496a55/styles/style.css#L155C1-L155C15

Met de # selector worden de style rules te specifiek. Hiermee kom je onherroepe;ijk in de problemen naarmate je meer code gaat schrijven en er meer variatie in de styling van elementen komt.

**Comment by fatimahilali** [comment]
Ik zal hier in de toekomst beter op letten en meer gebruik maken van minder specifieke selectors zoals klassen voor meer flexibiliteit.
