### ISSUE TITLE
De pagina is niet responsive

### ISSUE THREAD

**Issue by joostf** [fatimahilali/fix-the-flow-interactive-website#13]
<img width="367" alt="image" src="https://github.com/user-attachments/assets/ceb2cc4d-a5ec-4a68-baea-8548c2bf90ad" />

Elementen staan aan de boven- en onderkant van de pagina buiten beeld en de pagina is niet scrollbaar.

**Comment by fatimahilali** [comment]
Ik wist inderdaad dat de mobiele versie nog niet helemaal goed was. Door tijdgebrek heb ik er bewust voor gekozen het zo te laten zoals het nu is.
