### ISSUE TITLE
Indeling stylesheet niet overzichtelijk

### ISSUE THREAD

**Issue by joostf** [fatimahilali/fix-the-flow-interactive-website#14]
De indeling van je stylesheet is niet heel overzichtelijk.

Zorg voor consistente naamgeving, zet style rules die bij elkaar horen bij elkaar en volg de volgorde van de HTML.
Geef elke 'section' een duidelijk comment.

**Comment by fatimahilali** [comment]
inderdaad, de indeling van mijn stylesheet kan beter. Ik zal proberen de regels beter te groeperen, consistente naamgeving te gebruiken en duidelijke comments toe te voegen
