### ISSUE TITLE
Verberg nooit relevante content in een mobiele versie van de website

### ISSUE THREAD

**Issue by joostf** [fatimahilali/fix-the-flow-interactive-website#15]
https://github.com/fatimahilali/fix-the-flow-interactive-website/blob/97f2f3a4a67814e3f4c7c2679e00b9d18a496a55/styles/style.css#L505

**Comment by fatimahilali** [comment]
Dit is nieuw voor mij. Ik neem het mee en zal het toepassen in toekomstige projecten!
