### ISSUE TITLE
Is de DOMContentLoaded listener hier echt nodig?

### ISSUE THREAD

**Issue by joostf** [fatimahilali/fix-the-flow-interactive-website#16]
https://github.com/fatimahilali/fix-the-flow-interactive-website/blob/97f2f3a4a67814e3f4c7c2679e00b9d18a496a55/script/script.js#L34

**Comment by fatimahilali** [comment]
Het gebruik van DOMContentLoaded is toch nodig om ervoor te zorgen dat de code pas wordt uitgevoerd na het laden van de DOM?
