### ISSUE TITLE
Zorg voor betekenisvolle naamgeving

### ISSUE THREAD

**Issue by joostf** [fatimahilali/fix-the-flow-interactive-website#17]
https://github.com/fatimahilali/fix-the-flow-interactive-website/blob/97f2f3a4a67814e3f4c7c2679e00b9d18a496a55/script/script.js#L36

Uit de naam is niet op te maken wat er getoogled kan worden

**Comment by fatimahilali** [comment]
u hebt gelijk, een specifiekere naam zoals toggleEmailButton zou duidelijker zijn. Ik neem dit mee voor de toekomst!
