### ISSUE TITLE
Set geen inline style via JavaScript

### ISSUE THREAD

**Issue by joostf** [fatimahilali/fix-the-flow-interactive-website#18]
https://github.com/fatimahilali/fix-the-flow-interactive-website/blob/97f2f3a4a67814e3f4c7c2679e00b9d18a496a55/script/script.js#L94-L96

Je kan beter dynamische waardes doorgeven via custom properties en de styling verder afhandelen in CSS

https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/setProperty

**Comment by fatimahilali** [comment]
Het gebruik van setProperty voor custom properties is een nette aanpak om logica en styling te scheiden. Door de beperkte tijd laat ik het voor dit project zoals het is, maar ik neem deze tip zeker mee voor de toekomst!
