### ISSUE TITLE
Schrijf overzichtelijke JavaScript

### ISSUE THREAD

**Issue by joostf** [fatimahilali/fix-the-flow-interactive-website#19]
Je hebt veel JavaScript geschreven en het ziet er al heel netjes uit. 🚀
Omdat het zo veel is wordt het wel een beetje onoverzichtelijk. 🧹

Om je code overzichtelijker te maken kan je dit principe gebruiken:
https://github.com/fdnd-agency/.github/wiki/Conventies#javascript

Ook kan het helpen om het script, per functionaliteit, in verschillende scripts te verdelen. Dit dwingt je ook om de code die bij elkaar hoort bij elkaar te zetten.

Heb je deze code from scratch zelf geschreven of heb je gedeeltes overgenomen van een voorbeeld? In dat laatste geval is het netjes om te verwijzen naar bronnen!

**Comment by fatimahilali** [comment]
Ik begrijp dat de code overzichtelijker kan worden gemaakt. Ik zal bij een volgend project proberen de conventies te volgen die je hebt gedeeld, zoals het opdelen van de functionaliteiten in aparte scripts. Dat zal helpen om de structuur beter te organiseren.

Wat betreft de bron: de code heb ik grotendeels zelf geschreven, met enkele delen overgenomen en aangepast uit een eerder project . Mocht ik in de toekomst code uit externe bronnen gebruiken, dan zal ik ervoor zorgen dat ik deze bronnen duidelijk vermeld.
