### ISSUE TITLE
Generieke stijlelementen ontbreken

### ISSUE THREAD

**Issue by joostf** [fatimahilali/fix-the-flow-interactive-website#5]
Als je een component geïsoleerd uitwerkt, zorg er dan wel voor dat je generieke styling toepast. Nu wordt het lettertype dat op de body is gedefinieerd bijvoorbeeld niet getoond.

De oplossing hiervoor is het linken naar de generieke stylesheet die je in sprint 16 met je team hebt gemaakt: https://github.com/fdnd-task/look-and-feel-styleguide

**Comment by fatimahilali** [comment]
De generieke stylesheet was nog niet helemaal goed, en ik kreeg toestemming om een nieuwe te maken. Omdat ik niet op school aanwezig was, heb ik ervoor gekozen dit individueel uit te werken.
