### ISSUE TITLE
Gebruik consistente semantiek in je formulier

### ISSUE THREAD

**Issue by joostf** [fatimahilali/fix-the-flow-interactive-website#6]
https://github.com/fatimahilali/fix-the-flow-interactive-website/blob/97f2f3a4a67814e3f4c7c2679e00b9d18a496a55/index.html#L94-L105

In welke fieldset hoort deze `form-group`?

Let ook op je indenting en zorg voor consistente ruimte verdeling tussen elementen in je HTML

**Comment by fatimahilali** [comment]
Deze form-group hoort in de fieldset met contactgegevens om de structuur logisch te houden. Ik zal hier de volgende keer beter op letten.
