### ISSUE TITLE
Wat betekent 'Open e-mailadressen'

### ISSUE THREAD

**Issue by joostf** [fatimahilali/fix-the-flow-interactive-website#8]
<img width="239" alt="image" src="https://github.com/user-attachments/assets/adc6fcb5-5072-4eb9-985e-570c1155793f" />

Bedoel je _'Toon e-mailadressen'_?

Het is mij nu niet duidelijk waarom ik op dat knopje zou drukken.

**Comment by fatimahilali** [comment]
u  hebt gelijk, de tekst is niet duidelijk genoeg. Ik had oorspronkelijk een langere zin gebruikt, maar heb deze aangepast. Ik zie nu dat ik een foutje heb gemaakt; 'Toon e-mailadressen' is inderdaad een betere keuze en duidelijker voor de gebruiker
