### ISSUE TITLE
Gebruik betere semantiek om details te tonen?

### ISSUE THREAD

**Issue by joostf** [fatimahilali/fix-the-flow-interactive-website#9]
https://github.com/fatimahilali/fix-the-flow-interactive-website/blob/97f2f3a4a67814e3f4c7c2679e00b9d18a496a55/index.html#L34-L43

Zou je deze functionaliteit ook met een details / summary element kunnen oplossen?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

**Comment by fatimahilali** [comment]
Eerlijk gezegd heb ik hier niet specifiek op gefocust tijdens het maken van de code.  ik zal hier in de toekomst meer op letten.
